package com.medical.schoolMedical.exceptions;

public enum ErrorCode {
    USERNAME_EXISTS,
    CONTAINS_WHITESPACE,
    INVALID_PASSWORD,
    INTERNAL_ERROR,
    USERNAME_NOT_EXISTS,
    SAVE_HEALTH_CHECK_CONSENT_FAILED,
    HEALTH_CHECK_CONSENT_NOT_FOUND,
    SURVEY_EXPIRED,
//    Mã lỗi của health check record
    SAVE_HEALTH_CHECK_RECORD_FAILED,
    NOT_FOUND_SCHOOL_NURSE,
    HEALTH_CHECK_RECORD_NOT_FOUND,


}
